#!/ffp/bin/sh

export PN=bareos
export PV=15.2.2
export PR=1
#export E=$PV-Release-$PV
export SRC_URI="http://github.com/bareos/bareos/archive/Release/$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --with-sqlite3"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
#export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
